@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
package games.moegirl.sinocraft.sinofoundation.capability.block;

import com.mojang.math.MethodsReturnNonnullByDefault;
import net.minecraft.FieldsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;