plugins {
    id 'architectury-plugin' version '3.4-SNAPSHOT' apply false
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'com.gradleup.shadow' version '8.3.+' apply false
    id 'me.shedaniel.unified-publishing' version '0.1.+' apply false
}

apply from: 'gradle/scripts/base.gradle'

logger.lifecycle("Project SinoSeries. Build version: ${ext.getBuildVersion(rootProject)}")

// <editor-fold desc="Common">

def ENV = System.getenv()

allprojects {
    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }

        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }

        maven {
            name = 'FabricMC'
            url = 'https://maven.fabricmc.net/'
        }

        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }

        maven {
            name = 'Shedaniel'
            url = 'https://maven.shedaniel.me'
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }

            filter {
                includeGroup "maven.modrinth"
            }
        }

        maven {
            name = 'Yuluo'
            url = 'https://maven.yuluo.dev/repository/maven-public/'
        }
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'architectury-plugin'
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'me.shedaniel.unified-publishing'

    group = 'games.moegirl.sinocraft'

    architectury {
        minecraft = libs.versions.minecraft.get()
    }

    loom {
        silentMojangMappingsLicense()
        setEnableTransitiveAccessWideners true
        setEnableModProvidedJavadoc true

        interfaceInjection {
            enableDependencyInterfaceInjection = true
        }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${libs.versions.minecraft.get()}"

        mappings loom.layered() {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
        }
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    sourcesJar {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    processResources {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        exclude('mod_desc.txt')
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    publishing {
        repositories {
            mavenLocal()

            maven {
                name = 'YuluoMaven'

                def releaseUrl = 'https://maven.yuluo.dev/repository/maven-releases/'
                def snapshotUrl = 'https://maven.yuluo.dev/repository/maven-snapshots/'
                url = ENV.MOD_RELEASE ? releaseUrl : snapshotUrl

                credentials {
                    username Objects.requireNonNullElse(System.getenv('MOD_MAVEN_USER'), '')
                    password Objects.requireNonNullElse(System.getenv('MOD_MAVEN_PASS'), '')
                }
            }
        }
    }

    tasks.publishUnified.doFirst {
        if (!ENV.MOD_RELEASE) {
            println 'Hint: Running in debug mode, do NOT use publishUnified.'
        }
    }
}

ext.subModProjects.each { Project p ->
    configure(p) {
        loom {
            runConfigs.configureEach { config ->
                ideConfigGenerated = false
            }
        }

        publishing {
            publications {
                mavenJava(MavenPublication) {
                    version = rootProject.ext.getBuildVersion(p)
                    from components.java
                }
            }
        }

        processResources {
            var props = rootProject.ext.getExpandingProperties(p.parent, project.name.contains('fabric'))
            filesMatching(rootProject.ext.expandingFilesMatch as List<String>, { FileCopyDetails copy ->
                expand(props)
            })
        }
    }
}

ext.commonModProjects.each { Project p ->
    configure(p) {
        architectury {
            common(rootProject.ext.modPlatforms)
        }

        version = rootProject.ext.getVersion(p)

        if (project.hasProperty('mod_version')) {
            rootProject.logger.lifecycle("Project ${p.name} will use independent version string: ${version}")
        }

        loom {
            var aw = p.file("src/main/resources/${p.modid}.accesswidener")
            if (aw.exists()) {
                accessWidenerPath = aw
            }
        }

        sourceSets.main.resources {
            srcDir 'src/main/resources'
            srcDir 'src/generated/resources'
        }

        dependencies {
            // qyl27: Use fabric-loader in order to use EnvType class.
            modImplementation libs.fabric.loader

            if (p.name != 'sinocore') {
                api project(path: ':sinocore', configuration: 'namedElements')
            }

            compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
        }
    }
}

// </editor-fold>

// <editor-fold desc="Platform">

ext.platformProjects.each { Project p ->
    configure(p) {
        apply plugin: 'com.gradleup.shadow'

        version = p.parent.version

        loom {
            accessWidenerPath = p.parent.loom.accessWidenerPath
        }

        configurations {
            common {
                canBeResolved = true
                canBeConsumed = false
            }

            compileClasspath.extendsFrom common
            runtimeClasspath.extendsFrom common

            shadowBundle {
                canBeResolved = true
                canBeConsumed = false
            }
        }

        processResources {
            var props = rootProject.ext.getExpandingProperties(p.parent, project.name.contains('fabric'))
            filesMatching(rootProject.ext.expandingFilesMatch as List<String>, { FileCopyDetails copy ->
                expand(props)
            })
        }

        shadowJar {
            exclude 'architectury.common.json'

            configurations = [project.configurations.shadowBundle]
            archiveClassifier = 'dev-shadow'
        }

        remapJar {
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE

            injectAccessWidener = true
            input.set shadowJar.archiveFile
            dependsOn shadowJar
        }

        sourcesJar {
            var commonSources = p.parent.sourcesJar
            dependsOn commonSources
            from commonSources.archiveFile.map { zipTree(it) }
        }

        components.java {
            withVariantsFromConfiguration(p.configurations.shadowRuntimeElements) {
                skip()
            }
        }

        dependencies {
            if (!p.name.startsWith('sinocore')) {
                api project(path: ':sinocore', configuration: 'namedElements')
            }
        }

        parent.publish.dependsOn(publish)
        parent.publishUnified.dependsOn(publishUnified)
    }
}

ext.platformNeoForge.each { Project p ->
    configure(p) {
        architectury {
            platformSetupLoomIde()
            neoForge()
        }

        loom {
            runConfigs.configureEach { config ->
                ideConfigGenerated = false
            }
        }

        sourceSets.main.resources {
            srcDir p.parent.file('src/main/resources')
            srcDir p.parent.file('src/generated/resources')
        }

        dependencies {
            neoForge libs.neoforge

            common(project(path: p.parent.path, configuration: 'namedElements')) { transitive = false }
            shadowBundle project(path: p.parent.path, configuration: 'transformProductionNeoForge')
        }

        remapJar {
            if (p.parent.loom.accessWidenerPath.present) {
                atAccessWideners.add(p.parent.loom.accessWidenerPath.get().asFile.name)
            }
        }
    }
}

ext.platformFabric.each { Project p ->
    configure(p) {
        architectury {
            platformSetupLoomIde()
            fabric()
        }

        loom {
            runConfigs.configureEach { config ->
                ideConfigGenerated = false
            }
        }

        dependencies {
            modImplementation libs.fabric.loader
            modApi libs.fabric.api

            common(project(path: p.parent.path, configuration: 'namedElements')) { transitive = false }
            shadowBundle project(path: p.parent.path, configuration: 'transformProductionFabric')
        }
    }
}

// </editor-fold>

// <editor-fold desc="Meta">

ext.metaProjects.each { Project p ->
    configure(p) {
        version = rootProject.ext.sinoVersion

        configurations {
            common {
                canBeResolved = true
                canBeConsumed = false
            }

            compileClasspath.extendsFrom common
            runtimeClasspath.extendsFrom common
        }

        dependencies {
            rootProject.ext.commonModProjects.each { Project m ->
                common(project(path: m.path, configuration: 'namedElements')) { transitive true }
            }
        }

        processResources {
            var props = rootProject.ext.getExpandingProperties(p.parent, project.name.contains('fabric'))
            filesMatching(rootProject.ext.expandingFilesMatch as List<String>, { FileCopyDetails copy ->
                expand(props)
            })
        }

        publishing {
            publications {
                mavenJava(MavenPublication) {
                    version = rootProject.ext.getBuildVersion(p)
                    from components.java
                }
            }
        }
    }
}

// </editor-fold>

ext.refreshRunConfig()
