pluginManagement {
    repositories {
        maven { url 'https://maven.architectury.dev/' }
        maven { url 'https://maven.fabricmc.net/' }
        maven { url 'https://maven.neoforged.net/releases/' }
        gradlePluginPortal()
        mavenCentral()
        maven { url 'https://files.minecraftforge.net/maven/' }
    }
}

rootProject.name = 'sinoseries'

include ':mod-sinocore'
include ':mod-sinocore:neoforge'
include ':mod-sinocore:fabric'

include ':mod-sinobrush'
include ':mod-sinobrush:neoforge'
include ':mod-sinobrush:fabric'

include ':mod-sinodeco'
include ':mod-sinodeco:neoforge'
include ':mod-sinodeco:fabric'

include ':mod-sinotest'
include ':mod-sinotest:neoforge'
include ':mod-sinotest:fabric'

include ':meta'
include ':meta:neoforge'
include ':meta:fabric'
