pluginManagement {
    repositories {
        maven { url 'https://maven.architectury.dev/' }
        maven { url 'https://maven.fabricmc.net/' }
        maven { url 'https://maven.neoforged.net/releases/' }
        gradlePluginPortal()
        mavenCentral()
        maven { url 'https://files.minecraftforge.net/maven/' }
    }
}

rootProject.name = 'sinoseries'

include ':mod-sinocore'
include ':mod-sinocore:sinocore-neoforge'
include ':mod-sinocore:sinocore-fabric'

include ':mod-sinobrush'
include ':mod-sinobrush:sinobrush-neoforge'
include ':mod-sinobrush:sinobrush-fabric'

include ':mod-sinodeco'
include ':mod-sinodeco:sinodeco-neoforge'
include ':mod-sinodeco:sinodeco-fabric'

include ':mod-sinotest'
include ':mod-sinotest:sinotest-neoforge'
include ':mod-sinotest:sinotest-fabric'

include ':mod-meta'
include ':mod-meta:meta-neoforge'
include ':mod-meta:meta-fabric'
