plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    runs {
        client {
            configName = 'NeoForge Client'
            runDir = 'run/client'
        }

        server {
            configName = 'NeoForge Server'
            runDir = 'run/server'
        }

        project.rootProject.ext.subModProjects.each { Project p ->
            "data_${p.modid}" {
                data()

                ideConfigGenerated = true
                configName = "Data Generator ${p.modid}"

                programArgs '--all', '--mod', "${p.modid}",
                        '--output', p.file('src/generated/resources').absolutePath

                project.rootProject.ext.commonModProjects.each { Project m ->
                    programArgs '--existing', m.file('src/main/resources').absolutePath
                }
            }
        }
    }
}

configurations {
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge libs.neoforge

    modRuntimeOnly(libs.bundles.neoforge.runtime) { transitive = false }

    rootProject.ext.platformNeoForge.each { Project p ->
        implementation project(path: p.path, configuration: 'namedElements')

        if (p.parent.modid != 'sinotest') {
            include project(p.path)
        }
    }
}
