plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    runs {
        client {
            configName = 'Fabric Client'
            runDir = 'run/client'

            property 'fabric-tag-conventions-v2.missingTagTranslationWarning', 'VERBOSE'
        }

        server {
            configName = 'Fabric Server'
            runDir = 'run/server'

            property 'fabric-tag-conventions-v2.missingTagTranslationWarning', 'VERBOSE'
        }
    }

    mods {
        project.rootProject.ext.platformFabric.each { Project p ->
            "${p.parent.modid}" {
                sourceSet p.sourceSets.main
            }
        }
    }
}

configurations {
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation libs.fabric.loader
    modApi libs.fabric.api

    modRuntimeOnly(libs.bundles.fabric.runtime) {
        exclude group: 'com.terraformersmc', module: 'modmenu'
        exclude group: 'net.fabricmc', module: 'fabric-api'
    }

    rootProject.ext.platformFabric.each { Project p ->
        implementation project(path: p.path, configuration: 'namedElements')

        if (p.parent.modid != 'sinotest') {
            include project(p.path)
        }
    }
}
